# Generated by Django 4.2.11 on 2024-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("properties_owned", models.SmallIntegerField(default=0)),
                ("date_of_birth", models.DateField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "landlords",
            },
        ),
    ]
