# Generated by Django 4.2.11 on 2024-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="landlords",
            field=models.ManyToManyField(to="main.landlord"),
        ),
    ]
