# Generated by Django 4.2.11 on 2024-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_tenant_landlords"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=150)),
                ("zip_code", models.IntegerField()),
            ],
            options={
                "db_table": "locations",
            },
        ),
    ]
